ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: "cap.interface.nordcloud.workshop"
  name: "create"
  displayName: "create"
  description: "create action for nordcloud.workshop"
  documentationURL: https://example.com
  supportURL: https://example.com
  iconURL: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  maintainers:
    - email: dev@example.com
      name: Example Dev
      url: https://example.com

spec:
  input:
    parameters:
      input-parameters:
        typeRef:
          path: cap.type.nordcloud.workshop.create-input
          revision: 0.1.0
    typeInstances: {}

  output:
    typeInstances:
      config:
        typeRef:
          path: cap.type.nordcloud.workshop.config
          revision: 0.1.0
